## Arewa Data Science Academy
### Deep Learning Cohort2.0

#### Name: Nasiru Mahadi
#### Email: nasirumahadi@gmail.com
#### Title: Week 1 Solution


### Exercises Solution

2. Create a random tensor with shape (7, 7)

In [5]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(7, 7)

print(random_tensor)

tensor([[0.4495, 0.1205, 0.9621, 0.3350, 0.9417, 0.9625, 0.1185],
        [0.5680, 0.2874, 0.4092, 0.8802, 0.1351, 0.1606, 0.6266],
        [0.4712, 0.0851, 0.0246, 0.8953, 0.4444, 0.0354, 0.5192],
        [0.0259, 0.6052, 0.0338, 0.4932, 0.1266, 0.8389, 0.1127],
        [0.9515, 0.9097, 0.8308, 0.9146, 0.9490, 0.9070, 0.6534],
        [0.1018, 0.2130, 0.1071, 0.0677, 0.4838, 0.6273, 0.2169],
        [0.2637, 0.9071, 0.9520, 0.9903, 0.1447, 0.3849, 0.2376]])


2. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [10]:
 # Create second random tensor
 tensor2 = torch.rand(1, 7)

# Transpose tensor2
tensor2_transposed = tensor2.t()

# Transpose tensor2
tensor2_transposed = tensor2.t()

# Perform matrix multiplication using torch.matmul or @ operator
result_tensor = torch.matmul(random_tensor, tensor2_transposed)

print(result_tensor)

tensor([[1.4862],
        [1.4960],
        [0.9586],
        [0.5375],
        [2.6000],
        [0.4716],
        [1.8242]])


3. Set the random seed to 0 and do 2 & 3 over again.

In [11]:
# Set the random seed
torch.manual_seed(0)

# Create random tensor with shape (7, 7)
random_tensor = torch.rand(7, 7)

# Create second random tensor with shape (1, 7)
tensor2 = torch.rand(1, 7)

# Perform matrix multiplication
result_tensor = torch.matmul(random_tensor, tensor2_transposed)

print(result_tensor)

tensor([[1.2136],
        [1.7167],
        [1.6453],
        [1.8774],
        [0.8840],
        [1.2685],
        [0.9148]])


4.  Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one) If there is, set the GPU random seed to 1234

In [12]:
# Set the GPU random seed to 1234
torch.cuda.manual_seed(1234)  # For the current GPU


5. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [16]:
torch.manual_seed(1234)  # Set random seed

# Create two random tensors of shape (2, 3)
tensor1 = torch.rand(2, 3)
tensor2 = torch.rand(2, 3)

# Move tensors to the selected device (GPU or CPU)
tensor1 = tensor1.to(device)
tensor2 = tensor2.to(device)

print((tensor1, tensor2))

(tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]]), tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]]))


6. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors)

In [17]:
# Assuming tensor1 and tensor2 are already on the GPU
tensor2_transposed = tensor2.t()  # Transpose tensor2

# Perform matrix multiplication
result_tensor = torch.matmul(tensor1, tensor2_transposed)


print(result_tensor)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])


7. Find the maximum and minimum values of the output of 7.

In [18]:
# Find the maximum value
max_value = torch.max(result_tensor)
print("Maximum value:", max_value.item())  # .item() to get the scalar value

Maximum value: 0.5617256760597229


8. Find the maximum and minimum index values of the output of 7.

In [19]:
# Find the index of the maximum value
max_index = torch.argmax(result_tensor)
print("Index of maximum value:", max_index.item())  # .item() to get the scalar index

Index of maximum value: 3


9.  Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape

In [20]:
torch.manual_seed(7)  # Set the random seed

tensor1 = torch.rand(1, 1, 1, 10)

tensor2 = torch.squeeze(tensor1)


print("First tensor:", tensor1)
print("Shape of first tensor:", tensor1.shape)
print("Second tensor:", tensor2)
print("Shape of second tensor:", tensor2.shape)


First tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Shape of first tensor: torch.Size([1, 1, 1, 10])
Second tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Shape of second tensor: torch.Size([10])
